/* FILE GENERATED AUTOMATICALLY */

export type VariantSkin<T> = T extends "Altitude Odin"
    ? "Default"
    : T extends "Xenohunter Odin"
    ? "Default"
    : T extends "Rune Stone Odin"
    ? "Default"
    : T extends "Glitchpop Odin"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Nitro Odin"
    ? "Default"
    : T extends "Topotek Odin"
    ? "Default"
    : T extends ".EXE Odin"
    ? "Default"
    : T extends "Neo Frontier Odin"
    ? "Default" | "Gold" | "Silver" | "Copper"
    : T extends "Prime//2.0 Odin"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Prism III Odin"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Smite Odin"
    ? "Default"
    : T extends "Coalition: Cobra Odin"
    ? "Default" | "Blue" | "Red" | "Orange"
    : T extends "Lightwave Odin"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Sensation Odin"
    ? "Default"
    : T extends "Schema Odin"
    ? "Default"
    : T extends "Lycan's Bane Odin"
    ? "Default"
    : T extends "Reaver Odin"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Standard Odin"
    ? "Default"
    : T extends "Aerosol Odin"
    ? "Default"
    : T extends "BlastX Odin"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "VALORANT GO! Vol. 2 Ares"
    ? "Default"
    : T extends "Aristocrat Ares"
    ? "Default"
    : T extends "Endeavour Ares"
    ? "Default"
    : T extends "Nebula Ares"
    ? "Default"
    : T extends "Doodle Buds Ares"
    ? "Default" | "Tactifriends" | "LeagueofLegends"
    : T extends "Singularity Ares"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Rush Ares"
    ? "Default"
    : T extends "Hivemind Ares"
    ? "Default"
    : T extends "Spitfire Ares"
    ? "Default"
    : T extends "Digihex Ares"
    ? "Default" | "Red" | "Green" | "Gold"
    : T extends "Infantry Ares"
    ? "Default"
    : T extends "Goldwing Ares"
    ? "Default"
    : T extends "Outpost Ares"
    ? "Default"
    : T extends "Prism Ares"
    ? "Default"
    : T extends "Monstrocity Ares"
    ? "Default" | "Brown" | "Blue" | "Yellow"
    : T extends "Nunca Olvidados Ares"
    ? "Default" | "Living" | "Eternal"
    : T extends "Celestial Ares"
    ? "Default"
    : T extends "Magepunk Ares"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Minima Ares"
    ? "Default"
    : T extends "Ion Ares"
    ? "Default" | "Green" | "Yellow" | "Blue"
    : T extends "Oni Ares"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "9 Lives Ares"
    ? "Default" | "Raze" | "Reyna" | "Viper"
    : T extends "POLYfrog Ares"
    ? "Default"
    : T extends "Divine Swine Ares"
    ? "Default"
    : T extends "Jigsaw Ares"
    ? "Default" | "Killjoy" | "Astra" | "Yoru"
    : T extends "Premiere Collision Ares"
    ? "Default"
    : T extends "Sentinels of Light Ares"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Sakura Ares"
    ? "Default"
    : T extends "Snowfall Ares"
    ? "Default"
    : T extends "Titanmail Ares"
    ? "Default"
    : T extends "Standard Ares"
    ? "Default"
    : T extends "Immortalized Vandal"
    ? "Default" | "Orange" | "Blue" | "Green"
    : T extends "RGX 11z Pro Vandal"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "Altitude Vandal"
    ? "Default"
    : T extends "VALORANT GO! Vol. 2 Vandal"
    ? "Default"
    : T extends "Araxys Vandal"
    ? "Default" | "Purple" | "Black" | "Silver"
    : T extends "Neptune Vandal"
    ? "Default" | "Black"
    : T extends "Aristocrat Vandal"
    ? "Default"
    : T extends "Gaia's Vengeance Vandal"
    ? "Default" | "Blue" | "Green" | "Orange"
    : T extends "Endeavour Vandal"
    ? "Default"
    : T extends "Champions 2021 Vandal"
    ? "Default"
    : T extends "Champions 2023 Vandal"
    ? "Default"
    : T extends "Origin Vandal"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Starlit Odyssey Vandal"
    ? "Default" | "Twilight" | "Sunset" | "Midnight"
    : T extends "Glitchpop Vandal"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "ChronoVoid Vandal"
    ? "Default" | "Purple" | "Red" | "Black"
    : T extends "Prelude to Chaos Vandal"
    ? "Default" | "Green" | "White" | "Blue"
    : T extends "Elderflame Vandal"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Sarmad Vandal"
    ? "Default"
    : T extends "Nitro Vandal"
    ? "Default"
    : T extends "Hivemind Vandal"
    ? "Default"
    : T extends "Venturi Vandal"
    ? "Default"
    : T extends "Forsaken Vandal"
    ? "Default" | "Gold"
    : T extends "Team Ace Vandal"
    ? "Default"
    : T extends "Ruin Vandal"
    ? "Default"
    : T extends ".EXE Vandal"
    ? "Default"
    : T extends ".SYS Vandal"
    ? "Default"
    : T extends "Horizon Vandal"
    ? "Default"
    : T extends "Prime Vandal"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Avalanche Vandal"
    ? "Default"
    : T extends "Black.Market Vandal"
    ? "Default"
    : T extends "Prism II Vandal"
    ? "Default"
    : T extends "K/TAC Vandal"
    ? "Default"
    : T extends "Monstrocity Vandal"
    ? "Default" | "Brown" | "Blue" | "Yellow"
    : T extends "Nunca Olvidados Vandal"
    ? "Default" | "Living" | "Eternal"
    : T extends "Luxe Vandal"
    ? "Default"
    : T extends "Magepunk Vandal"
    ? "Default" | "Green" | "Black/Red" | "Yellow"
    : T extends "Silvanus Vandal"
    ? "Default"
    : T extends "Crimsonbeast Vandal"
    ? "Default"
    : T extends "Ion Vandal"
    ? "Default" | "Green" | "Yellow" | "Blue"
    : T extends "Oni Vandal"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Cryostasis Vandal"
    ? "Default"
    : T extends "Luna Vandal"
    ? "Default"
    : T extends "Sensation Vandal"
    ? "Default"
    : T extends "Sentinels of Light Vandal"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Sakura Vandal"
    ? "Default"
    : T extends "Schema Vandal"
    ? "Default"
    : T extends "Lycan's Bane Vandal"
    ? "Default"
    : T extends "Reaver Vandal"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Vandal"
    ? "Default"
    : T extends "Cavalier Vandal"
    ? "Default"
    : T extends "Titanmail Vandal"
    ? "Default"
    : T extends "Standard Vandal"
    ? "Default"
    : T extends "NO LIMITS Vandal"
    ? "Default"
    : T extends "Depths Vandal"
    ? "Default"
    : T extends "Ego Vandal"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Wasteland Vandal"
    ? "Default"
    : T extends "Winterwunderland Vandal"
    ? "Default"
    : T extends "Araxys Bulldog"
    ? "Default" | "Purple" | "Black" | "Silver"
    : T extends "Radiant Entertainment System Bulldog"
    ? "Default" | "DanceFever" | "K.nockO.ut!!"
    : T extends "Aristocrat Bulldog"
    ? "Default"
    : T extends "Endeavour Bulldog"
    ? "Default"
    : T extends "Spectrum Bulldog"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Striker Bulldog"
    ? "Default" | "Green/Yellow/Black" | "Pink/Teal/Purple" | "Blue/White/Red"
    : T extends "Rune Stone Bulldog"
    ? "Default"
    : T extends "Undercity Bulldog"
    ? "Default"
    : T extends "Glitchpop Bulldog"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Rush Bulldog"
    ? "Default"
    : T extends "Velocity Bulldog"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Shimmer Bulldog"
    ? "Default" | "Gold" | "Red" | "Teal"
    : T extends "Digihex Bulldog"
    ? "Default" | "Red" | "Green" | "Gold"
    : T extends "Horizon Bulldog"
    ? "Default"
    : T extends "Black.Market Bulldog"
    ? "Default"
    : T extends "Bound Bulldog"
    ? "Default"
    : T extends "K/TAC Bulldog"
    ? "Default"
    : T extends "Couture Bulldog"
    ? "Default"
    : T extends "Nunca Olvidados Bulldog"
    ? "Default" | "Living" | "Eternal"
    : T extends "Genesis Bulldog"
    ? "Default"
    : T extends "Oni Bulldog"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Cryostasis Bulldog"
    ? "Default"
    : T extends "Hue Shift Bulldog"
    ? "Default"
    : T extends "POLYfox Bulldog"
    ? "Default"
    : T extends "Protocol 781-A Bulldog"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Premiere Collision Bulldog"
    ? "Default"
    : T extends "Infinity Bulldog"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Bulldog"
    ? "Default"
    : T extends "Tilde Bulldog"
    ? "Default" | "Red" | "Purple" | "Green"
    : T extends "Gridcrash Bulldog"
    ? "Default"
    : T extends "NO LIMITS Bulldog"
    ? "Default"
    : T extends "Convex Bulldog"
    ? "Default"
    : T extends "Depths Bulldog"
    ? "Default"
    : T extends "Varnish Bulldog"
    ? "Default"
    : T extends "Task Force 809 Phantom"
    ? "Default"
    : T extends "RGX 11z Pro Phantom"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "Xenohunter Phantom"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Phantom"
    ? "Default"
    : T extends "Radiant Entertainment System Phantom"
    ? "Default" | "DanceFever" | "K.nockO.ut!!"
    : T extends "Spectrum Phantom"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Piedra del Sol Phantom"
    ? "Default"
    : T extends "Composite Phantom"
    ? "Default"
    : T extends "Champions 2022 Phantom"
    ? "Default"
    : T extends "Radiant Crisis 001 Phantom"
    ? "Default"
    : T extends "Nebula Phantom"
    ? "Default"
    : T extends "Undercity Phantom"
    ? "Default"
    : T extends "Glitchpop Phantom"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "ChronoVoid Phantom"
    ? "Default" | "Purple" | "Red" | "Black"
    : T extends "Abyssal Phantom"
    ? "Default"
    : T extends "Doodle Buds Phantom"
    ? "Default" | "Tactifriends" | "LeagueofLegends"
    : T extends "Singularity Phantom"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Sarmad Phantom"
    ? "Default"
    : T extends "Rush Phantom"
    ? "Default"
    : T extends "Velocity Phantom"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Team Ace Phantom"
    ? "Default"
    : T extends "Topotek Phantom"
    ? "Default"
    : T extends "Neo Frontier Phantom"
    ? "Default" | "Gold" | "Silver" | "Copper"
    : T extends "Soulstrife Phantom"
    ? "Default"
    : T extends "Prime//2.0 Phantom"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Avalanche Phantom"
    ? "Default"
    : T extends "Bound Phantom"
    ? "Default"
    : T extends "Prism Phantom"
    ? "Default"
    : T extends "Serenity Phantom"
    ? "Default"
    : T extends "Ruination Phantom"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Phantom"
    ? "Default"
    : T extends "Kohaku & Matsuba Phantom"
    ? "Default" | "Dark"
    : T extends "Smite Phantom"
    ? "Default"
    : T extends "Daydreams Phantom"
    ? "Default"
    : T extends "Celestial Phantom"
    ? "Default"
    : T extends "Magepunk Phantom"
    ? "Default" | "Green" | "Black/Red" | "Yellow"
    : T extends "Spline Phantom"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Phantom"
    ? "Default"
    : T extends "Galleria Phantom"
    ? "Default"
    : T extends "Silvanus Phantom"
    ? "Default"
    : T extends "Ion Phantom"
    ? "Default"
    : T extends "Oni Phantom"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "9 Lives Phantom"
    ? "Default" | "Raze" | "Reyna" | "Viper"
    : T extends "Hue Shift Phantom"
    ? "Default"
    : T extends "Aero Phantom"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "Artisan Phantom"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Protocol 781-A Phantom"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Lightwave Phantom"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Snowfall Phantom"
    ? "Default"
    : T extends "Reaver Phantom"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Recon Phantom"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Phantom"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Reverie Phantom"
    ? "Default"
    : T extends "Standard Phantom"
    ? "Default"
    : T extends "Tigris Phantom"
    ? "Default"
    : T extends "BlastX Phantom"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Winterwunderland Phantom"
    ? "Default"
    : T extends "Piedra del Sol Judge"
    ? "Default"
    : T extends "Undercity Judge"
    ? "Default"
    : T extends "Glitchpop Judge"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "ChronoVoid Judge"
    ? "Default" | "Purple" | "Red" | "Black"
    : T extends "Elderflame Judge"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Rush Judge"
    ? "Default"
    : T extends "Team Ace Judge"
    ? "Default"
    : T extends "Shimmer Judge"
    ? "Default" | "Gold" | "Red" | "Teal"
    : T extends ".EXE Judge"
    ? "Default"
    : T extends "Digihex Judge"
    ? "Default" | "Red" | "Green" | "Gold"
    : T extends "Goldwing Judge"
    ? "Default"
    : T extends "Hydrodip Judge"
    ? "Default"
    : T extends "Outpost Judge"
    ? "Default"
    : T extends "Bound Judge"
    ? "Default"
    : T extends "Prism III Judge"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Serenity Judge"
    ? "Default"
    : T extends "Kohaku & Matsuba Judge"
    ? "Default" | "Dark"
    : T extends "Smite Judge"
    ? "Default"
    : T extends "Daydreams Judge"
    ? "Default"
    : T extends "Iridian Thorn Judge"
    ? "Default"
    : T extends "Celestial Judge"
    ? "Default"
    : T extends "Luxe Judge"
    ? "Default"
    : T extends "Coalition: Cobra Judge"
    ? "Default" | "Blue" | "Red" | "Orange"
    : T extends "Crimsonbeast Judge"
    ? "Default"
    : T extends "POLYfox Judge"
    ? "Default"
    : T extends "Divine Swine Judge"
    ? "Default"
    : T extends "Jigsaw Judge"
    ? "Default" | "Skye" | "Astra" | "Yoru"
    : T extends "Sensation Judge"
    ? "Default"
    : T extends "Snowfall Judge"
    ? "Default"
    : T extends "Standard Judge"
    ? "Default"
    : T extends "Tilde Judge"
    ? "Default" | "Red" | "Purple" | "Green"
    : T extends "Gridcrash Judge"
    ? "Default"
    : T extends "Convex Judge"
    ? "Default"
    : T extends "Varnish Judge"
    ? "Default"
    : T extends "Altitude Bucky"
    ? "Default"
    : T extends "Xenohunter Bucky"
    ? "Default"
    : T extends "Piedra del Sol Bucky"
    ? "Default"
    : T extends "Origin Bucky"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Radiant Crisis 001 Bucky"
    ? "Default"
    : T extends "Red Alert Bucky"
    ? "Default"
    : T extends "Surge Bucky"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Topotek Bucky"
    ? "Default"
    : T extends ".SYS Bucky"
    ? "Default"
    : T extends "Horizon Bucky"
    ? "Default"
    : T extends "Monarch Bucky"
    ? "Default"
    : T extends "Hydrodip Bucky"
    ? "Default"
    : T extends "Prime//2.0 Bucky"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Prism II Bucky"
    ? "Default"
    : T extends "Kingdom Bucky"
    ? "Default"
    : T extends "Iridian Thorn Bucky"
    ? "Default"
    : T extends "Magepunk Bucky"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Galleria Bucky"
    ? "Default"
    : T extends "Genesis Bucky"
    ? "Default"
    : T extends "Ion Bucky"
    ? "Default"
    : T extends "Oni Bucky"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Artisan Bucky"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Lightwave Bucky"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Gravitational Uranium Neuroblaster Bucky"
    ? "Default" | "Chrome" | "Black" | "Red/Blue"
    : T extends "Cavalier Bucky"
    ? "Default"
    : T extends "Titanmail Bucky"
    ? "Default"
    : T extends "Standard Bucky"
    ? "Default"
    : T extends "Aerosol Bucky"
    ? "Default"
    : T extends "Task Force 809 Frenzy"
    ? "Default"
    : T extends "RGX 11z Pro Frenzy"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "Xenohunter Frenzy"
    ? "Default"
    : T extends "RagnaRocker Frenzy"
    ? "Default"
    : T extends "Origin Frenzy"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Glitchpop Frenzy"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Elderflame Frenzy"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Sarmad Frenzy"
    ? "Default"
    : T extends "Rush Frenzy"
    ? "Default"
    : T extends "Venturi Frenzy"
    ? "Default"
    : T extends "Team Ace Frenzy"
    ? "Default"
    : T extends "Swooping Frenzy"
    ? "Default"
    : T extends "Horizon Frenzy"
    ? "Default"
    : T extends "Monarch Frenzy"
    ? "Default"
    : T extends "Hydrodip Frenzy"
    ? "Default"
    : T extends "Prime//2.0 Frenzy"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Couture Frenzy"
    ? "Default"
    : T extends "Blush Frenzy"
    ? "Default"
    : T extends "Nunca Olvidados Frenzy"
    ? "Default" | "Living" | "Eternal"
    : T extends "Celestial Frenzy"
    ? "Default"
    : T extends "Coalition: Cobra Frenzy"
    ? "Default" | "Blue" | "Red" | "Orange"
    : T extends "Moondash Frenzy"
    ? "Default"
    : T extends "Ion Frenzy"
    ? "Default" | "Green" | "Yellow" | "Blue"
    : T extends "Oni Frenzy"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Spitfire Frenzy"
    ? "Default"
    : T extends "Aero Frenzy"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "Divine Swine Frenzy"
    ? "Default"
    : T extends "Lightwave Frenzy"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Sensation Frenzy"
    ? "Default"
    : T extends "Titanmail Frenzy"
    ? "Default"
    : T extends "Live Wire Frenzy"
    ? "Default"
    : T extends "Standard Frenzy"
    ? "Default"
    : T extends "BlastX Frenzy"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Resolution Classic"
    ? "Default"
    : T extends "RGX 11z Pro Classic"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 2 Classic"
    ? "Default"
    : T extends "Spectrum Classic"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Pistolinha Classic"
    ? "Default"
    : T extends "Striker Classic"
    ? "Default" | "Green/Yellow/Black" | "Pink/Teal/Purple" | "Blue/White/Red"
    : T extends "Radiant Crisis 001 Classic"
    ? "Default"
    : T extends "Red Alert Classic"
    ? "Default"
    : T extends "Undercity Classic"
    ? "Default"
    : T extends "Glitchpop Classic"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Finesse Classic"
    ? "Default"
    : T extends "Surge Classic"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Songsteel Classic"
    ? "Default"
    : T extends "Forsaken Classic"
    ? "Default" | "Gold"
    : T extends "Shimmer Classic"
    ? "Default" | "Gold" | "Red" | "Teal"
    : T extends "FIRE/arm Classic"
    ? "Default"
    : T extends "Goldwing Classic"
    ? "Default"
    : T extends "Prime Classic"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Avalanche Classic"
    ? "Default"
    : T extends "Black.Market Classic"
    ? "Default"
    : T extends "Bound Classic"
    ? "Default"
    : T extends "Prism III Classic"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Kingdom Classic"
    ? "Default"
    : T extends "Kohaku & Matsuba Classic"
    ? "Default" | "Dark"
    : T extends "Smite Classic"
    ? "Default"
    : T extends "Daydreams Classic"
    ? "Default"
    : T extends "Spline Classic"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Galleria Classic"
    ? "Default"
    : T extends "Cryostasis Classic"
    ? "Default"
    : T extends "9 Lives Classic"
    ? "Default" | "Raze" | "Reyna" | "Viper"
    : T extends "Premiere Collision Classic"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Classic"
    ? "Default" | "Chrome" | "Black" | "Red/Blue"
    : T extends "Sakura Classic"
    ? "Default"
    : T extends "Snowfall Classic"
    ? "Default"
    : T extends "Infinity Classic"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Reverie Classic"
    ? "Default"
    : T extends "Standard Classic"
    ? "Default"
    : T extends "Final Chamber Classic"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Ghost"
    ? "Default"
    : T extends "Radiant Entertainment System Ghost"
    ? "Default" | "DanceFever" | "K.nockO.ut!!"
    : T extends "Gaia's Vengeance Ghost"
    ? "Default" | "Blue" | "Green" | "Orange"
    : T extends "Endeavour Ghost"
    ? "Default"
    : T extends "Piedra del Sol Ghost"
    ? "Default"
    : T extends "Starlit Odyssey Ghost"
    ? "Default" | "Twilight" | "Sunset" | "Midnight"
    : T extends "Topotek Ghost"
    ? "Default"
    : T extends "Spitfire Ghost"
    ? "Default"
    : T extends ".EXE Ghost"
    ? "Default"
    : T extends "Hush Ghost"
    ? "Default"
    : T extends "Soulstrife Ghost"
    ? "Default"
    : T extends "Digihex Ghost"
    ? "Default" | "Red" | "Green" | "Gold"
    : T extends "Infantry Ghost"
    ? "Default"
    : T extends "Goldwing Ghost"
    ? "Default"
    : T extends "Outpost Ghost"
    ? "Default"
    : T extends "Prism Ghost"
    ? "Default"
    : T extends "Serenity Ghost"
    ? "Default"
    : T extends "Ruination Ghost"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Luxe Ghost"
    ? "Default"
    : T extends "Magepunk Ghost"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Artisan Ghost"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Jigsaw Ghost"
    ? "Default" | "Skye" | "Killjoy" | "Astra"
    : T extends "Luna Ghost"
    ? "Default"
    : T extends "Eclipse Ghost"
    ? "Default"
    : T extends "Lycan's Bane Ghost"
    ? "Default"
    : T extends "Reaver Ghost"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Ghost"
    ? "Default"
    : T extends "Sovereign Ghost"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Recon Ghost"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Cavalier Ghost"
    ? "Default"
    : T extends "Standard Ghost"
    ? "Default"
    : T extends "Gridcrash Ghost"
    ? "Default"
    : T extends "NO LIMITS Ghost"
    ? "Default"
    : T extends "Depths Ghost"
    ? "Default"
    : T extends "Ego Ghost"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Vendetta Ghost"
    ? "Default"
    : T extends "Winterwunderland Ghost"
    ? "Default"
    : T extends "Soul Silencer Ghost"
    ? "Default"
    : T extends "Wayfarer Sheriff"
    ? "Default"
    : T extends "Immortalized Sheriff"
    ? "Default" | "Orange" | "Blue" | "Green"
    : T extends "Altitude Sheriff"
    ? "Default"
    : T extends "Aristocrat Sheriff"
    ? "Default"
    : T extends "Composite Sheriff"
    ? "Default"
    : T extends "Nebula Sheriff"
    ? "Default"
    : T extends "ChronoVoid Sheriff"
    ? "Default" | "Purple" | "Red" | "Black"
    : T extends "Abyssal Sheriff"
    ? "Default"
    : T extends "Singularity Sheriff"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Surge Sheriff"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends ".SYS Sheriff"
    ? "Default"
    : T extends "Neo Frontier Sheriff"
    ? "Default" | "Gold" | "Silver" | "Copper"
    : T extends "Protektor Sheriff"
    ? "Default"
    : T extends "Prism II Sheriff"
    ? "Default"
    : T extends "K/TAC Sheriff"
    ? "Default"
    : T extends "Monstrocity Sheriff"
    ? "Default" | "Brown" | "Blue" | "Yellow"
    : T extends "Iridian Thorn Sheriff"
    ? "Default"
    : T extends "Magepunk Sheriff"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Signature Sheriff"
    ? "Default"
    : T extends "Minima Sheriff"
    ? "Default"
    : T extends "Silvanus Sheriff"
    ? "Default"
    : T extends "Crimsonbeast Sheriff"
    ? "Default"
    : T extends "Ion Sheriff"
    ? "Default"
    : T extends "POLYfox Sheriff"
    ? "Default"
    : T extends "POLYfrog Sheriff"
    ? "Default"
    : T extends "Protocol 781-A Sheriff"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Lightwave Sheriff"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Sentinels of Light Sheriff"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Sakura Sheriff"
    ? "Default"
    : T extends "Peacekeeper Sheriff"
    ? "Default"
    : T extends "Schema Sheriff"
    ? "Default"
    : T extends "Reaver Sheriff"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Standard Sheriff"
    ? "Default"
    : T extends "Convex Sheriff"
    ? "Default"
    : T extends "Varnish Sheriff"
    ? "Default"
    : T extends "Wasteland Sheriff"
    ? "Default"
    : T extends "Game Over Sheriff"
    ? "Default"
    : T extends "Arcane Sheriff"
    ? "Default"
    : T extends "Death Wish Sheriff"
    ? "Default"
    : T extends "Sidekick Shorty"
    ? "Default"
    : T extends "Araxys Shorty"
    ? "Default" | "Purple" | "Black" | "Silver"
    : T extends "Neptune Shorty"
    ? "Default" | "Black"
    : T extends "Karabasan Shorty"
    ? "Default"
    : T extends "Rune Stone Shorty"
    ? "Default"
    : T extends "Prelude to Chaos Shorty"
    ? "Default" | "Green" | "White" | "Blue"
    : T extends "Doodle Buds Shorty"
    ? "Default" | "Tactifriends" | "LeagueofLegends"
    : T extends "Hivemind Shorty"
    ? "Default"
    : T extends "Velocity Shorty"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Ruin Shorty"
    ? "Default"
    : T extends "Monarch Shorty"
    ? "Default"
    : T extends "Prism II Shorty"
    ? "Default"
    : T extends "Wunderkind Shorty"
    ? "Default"
    : T extends "Genesis Shorty"
    ? "Default"
    : T extends "Oni Shorty"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Snakebite Shorty"
    ? "Default"
    : T extends "Hue Shift Shorty"
    ? "Default"
    : T extends "Standard Shorty"
    ? "Default"
    : T extends "Aerosol Shorty"
    ? "Default"
    : T extends "Tilde Shorty"
    ? "Default" | "Red" | "Purple" | "Green"
    : T extends "Tigris Shorty"
    ? "Default"
    : T extends "Wayfinder Shorty"
    ? "Default"
    : T extends "Wasteland Shorty"
    ? "Default"
    : T extends "RGX 11z Pro Operator"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 2 Operator"
    ? "Default"
    : T extends "Araxys Operator"
    ? "Default" | "Purple" | "Black" | "Silver"
    : T extends "Radiant Entertainment System Operator"
    ? "Default" | "DanceFever" | "K.nockO.ut!!"
    : T extends "Endeavour Operator"
    ? "Default"
    : T extends "Origin Operator"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Striker Operator"
    ? "Default" | "Green/Yellow/Black" | "Pink/Teal/Purple" | "Blue/White/Red"
    : T extends "Red Alert Operator"
    ? "Default"
    : T extends "Glitchpop Operator"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Prelude to Chaos Operator"
    ? "Default" | "Green" | "White" | "Blue"
    : T extends "Elderflame Operator"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Nitro Operator"
    ? "Default"
    : T extends "Forsaken Operator"
    ? "Default" | "Gold"
    : T extends "Team Ace Operator"
    ? "Default"
    : T extends "Spitfire Operator"
    ? "Default"
    : T extends "Infantry Operator"
    ? "Default"
    : T extends "Prism Operator"
    ? "Default"
    : T extends "K/TAC Operator"
    ? "Default"
    : T extends "Kohaku & Matsuba Operator"
    ? "Default" | "Dark"
    : T extends "Blush Operator"
    ? "Default"
    : T extends "Daydreams Operator"
    ? "Default"
    : T extends "Iridian Thorn Operator"
    ? "Default"
    : T extends "Luxe Operator"
    ? "Default"
    : T extends "Magepunk Operator"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Spline Operator"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Operator"
    ? "Default"
    : T extends "Silvanus Operator"
    ? "Default"
    : T extends "Genesis Operator"
    ? "Default"
    : T extends "Ion Operator"
    ? "Default"
    : T extends "Cryostasis Operator"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Operator"
    ? "Default" | "Chrome" | "Black" | "Red/Blue"
    : T extends "Sentinels of Light Operator"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Operator"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Operator"
    ? "Default"
    : T extends "Cavalier Operator"
    ? "Default"
    : T extends "Standard Operator"
    ? "Default"
    : T extends "Aerosol Operator"
    ? "Default"
    : T extends "Tilde Operator"
    ? "Default" | "Red" | "Purple" | "Green"
    : T extends "Tigris Operator"
    ? "Default"
    : T extends "Convex Operator"
    ? "Default"
    : T extends "Immortalized Guardian"
    ? "Default" | "Orange" | "Blue" | "Green"
    : T extends "RGX 11z Pro Guardian"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 1 Guardian"
    ? "Default"
    : T extends "Neptune Guardian"
    ? "Default" | "Black"
    : T extends "Gaia's Vengeance Guardian"
    ? "Default" | "Blue" | "Green" | "Orange"
    : T extends "Spectrum Guardian"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Starlit Odyssey Guardian"
    ? "Default" | "Twilight" | "Sunset" | "Midnight"
    : T extends "Nebula Guardian"
    ? "Default"
    : T extends "Abyssal Guardian"
    ? "Default"
    : T extends "Nitro Guardian"
    ? "Default"
    : T extends "Songsteel Guardian"
    ? "Default"
    : T extends "Spitfire Guardian"
    ? "Default"
    : T extends "Ruin Guardian"
    ? "Default"
    : T extends "Soulstrife Guardian"
    ? "Default"
    : T extends "Infantry Guardian"
    ? "Default"
    : T extends "Hydrodip Guardian"
    ? "Default"
    : T extends "Prime Guardian"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Ruination Guardian"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Blush Guardian"
    ? "Default"
    : T extends "Magepunk Guardian"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Signature Guardian"
    ? "Default"
    : T extends "Galleria Guardian"
    ? "Default"
    : T extends "Moondash Guardian"
    ? "Default"
    : T extends "Oni Guardian"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "9 Lives Guardian"
    ? "Default" | "Raze" | "Reyna" | "Viper"
    : T extends "Aero Guardian"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "POLYfox Guardian"
    ? "Default"
    : T extends "Jigsaw Guardian"
    ? "Default" | "Skye" | "Killjoy" | "Yoru"
    : T extends "Reaver Guardian"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Guardian"
    ? "Default"
    : T extends "Sovereign Guardian"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Recon Guardian"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Guardian"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Reverie Guardian"
    ? "Default"
    : T extends "Standard Guardian"
    ? "Default"
    : T extends "Ego Guardian"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Task Force 809 Marshal"
    ? "Default"
    : T extends "Gaia's Vengeance Marshal"
    ? "Default" | "Blue" | "Green" | "Orange"
    : T extends "Composite Marshal"
    ? "Default"
    : T extends "Rune Stone Marshal"
    ? "Default"
    : T extends "Doodle Buds Marshal"
    ? "Default" | "Tactifriends" | "LeagueofLegends"
    : T extends "Songsteel Marshal"
    ? "Default"
    : T extends "Venturi Marshal"
    ? "Default"
    : T extends "Ruin Marshal"
    ? "Default"
    : T extends "Neo Frontier Marshal"
    ? "Default" | "Gold" | "Silver" | "Copper"
    : T extends "Monarch Marshal"
    ? "Default"
    : T extends "Avalanche Marshal"
    ? "Default"
    : T extends "Black.Market Marshal"
    ? "Default"
    : T extends "Couture Marshal"
    ? "Default"
    : T extends "Magepunk Marshal"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Signature Marshal"
    ? "Default"
    : T extends "Coalition: Cobra Marshal"
    ? "Default" | "Blue" | "Red" | "Orange"
    : T extends "Galleria Marshal"
    ? "Default"
    : T extends "Crimsonbeast Marshal"
    ? "Default"
    : T extends "Moondash Marshal"
    ? "Default"
    : T extends "POLYfrog Marshal"
    ? "Default"
    : T extends "Divine Swine Marshal"
    ? "Default"
    : T extends "Artisan Marshal"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Luna Marshal"
    ? "Default"
    : T extends "Premiere Collision Marshal"
    ? "Default"
    : T extends "Sovereign Marshal"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Reverie Marshal"
    ? "Default"
    : T extends "Standard Marshal"
    ? "Default"
    : T extends "Wasteland Marshal"
    ? "Default"
    : T extends "Winterwunderland Marshal"
    ? "Default"
    : T extends "Task Force 809 Spectre"
    ? "Default"
    : T extends "RGX 11z Pro Spectre"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 1 Spectre"
    ? "Default"
    : T extends "Neptune Spectre"
    ? "Default" | "Black"
    : T extends "Striker Spectre"
    ? "Default" | "Green/Yellow/Black" | "Pink/Teal/Purple" | "Blue/White/Red"
    : T extends "Radiant Crisis 001 Spectre"
    ? "Default"
    : T extends "Starlit Odyssey Spectre"
    ? "Default" | "Twilight" | "Sunset" | "Midnight"
    : T extends "Abyssal Spectre"
    ? "Default"
    : T extends "Singularity Spectre"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Sarmad Spectre"
    ? "Default"
    : T extends "Hivemind Spectre"
    ? "Default"
    : T extends "Venturi Spectre"
    ? "Default"
    : T extends "Forsaken Spectre"
    ? "Default" | "Gold"
    : T extends "Velocity Spectre"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Soulstrife Spectre"
    ? "Default"
    : T extends "Infantry Spectre"
    ? "Default"
    : T extends "Horizon Spectre"
    ? "Default"
    : T extends "Prime Spectre"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Avalanche Spectre"
    ? "Default"
    : T extends "Prism Spectre"
    ? "Default"
    : T extends "Serenity Spectre"
    ? "Default"
    : T extends "Ruination Spectre"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Spectre"
    ? "Default"
    : T extends "Blush Spectre"
    ? "Default"
    : T extends "Monstrocity Spectre"
    ? "Default" | "Brown" | "Blue" | "Yellow"
    : T extends "Luxe Spectre"
    ? "Default"
    : T extends "Magepunk Spectre"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Spline Spectre"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Spectre"
    ? "Default"
    : T extends "Ion Spectre"
    ? "Default" | "Green" | "Yellow" | "Blue"
    : T extends "Hue Shift Spectre"
    ? "Default"
    : T extends "Aero Spectre"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "POLYfrog Spectre"
    ? "Default"
    : T extends "Protocol 781-A Spectre"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Luna Spectre"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Spectre"
    ? "Default" | "Chrome" | "Black" | "Red/Blue"
    : T extends "Reaver Spectre"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Recon Spectre"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Spectre"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Spectre"
    ? "Default"
    : T extends "Tigris Spectre"
    ? "Default"
    : T extends "NO LIMITS Spectre"
    ? "Default"
    : T extends "Convex Spectre"
    ? "Default"
    : T extends "BlastX Spectre"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Wasteland Spectre"
    ? "Default"
    : T extends "Immortalized Stinger"
    ? "Default" | "Orange" | "Blue" | "Green"
    : T extends "RGX 11z Pro Stinger"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "Aristocrat Stinger"
    ? "Default"
    : T extends "Composite Stinger"
    ? "Default"
    : T extends "Red Alert Stinger"
    ? "Default"
    : T extends "Prelude to Chaos Stinger"
    ? "Default" | "Green" | "White" | "Blue"
    : T extends "Doodle Buds Stinger"
    ? "Default" | "Tactifriends" | "LeagueofLegends"
    : T extends "Surge Stinger"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Shimmer Stinger"
    ? "Default" | "Gold" | "Red" | "Teal"
    : T extends ".SYS Stinger"
    ? "Default"
    : T extends "Prism II Stinger"
    ? "Default"
    : T extends "Couture Stinger"
    ? "Default"
    : T extends "Signature Stinger"
    ? "Default"
    : T extends "Silvanus Stinger"
    ? "Default"
    : T extends "Moondash Stinger"
    ? "Default"
    : T extends "Sensation Stinger"
    ? "Default"
    : T extends "Sakura Stinger"
    ? "Default"
    : T extends "Schema Stinger"
    ? "Default"
    : T extends "Lycan's Bane Stinger"
    ? "Default"
    : T extends "Sovereign Stinger"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Cavalier Stinger"
    ? "Default"
    : T extends "Standard Stinger"
    ? "Default"
    : T extends "Gridcrash Stinger"
    ? "Default"
    : T extends "Depths Stinger"
    ? "Default"
    : T extends "Ego Stinger"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Varnish Stinger"
    ? "Default"
    : T extends "Task Force 809 Knife"
    ? "Default"
    : T extends "RGX 11z Pro Blade"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "RGX 11z Pro Firefly"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Altitude Knuckle Knife"
    ? "Default"
    : T extends "Xenohunter Knife"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Knife"
    ? "Default"
    : T extends "Yoru's Stylish Butterfly Comb"
    ? "Default"
    : T extends "Araxys Bio Harvester"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Neptune Anchor"
    ? "Default"
    : T extends "Power Fist"
    ? "Default" | "DanceFever" | "K.nockO.ut!!"
    : T extends "Gaia's Wrath"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Waveform"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Obsidiana"
    ? "Default"
    : T extends "Composite Knife"
    ? "Default"
    : T extends "Champions 2021 Karambit"
    ? "Default"
    : T extends "Champions 2022 Butterfly Knife"
    ? "Default"
    : T extends "Champions 2023 Kunai"
    ? "Default"
    : T extends "Origin Crescent Blade"
    ? "Default"
    : T extends "Striker Knife"
    ? "Default" | "Green/Yellow/Black" | "Pink/Teal/Purple" | "Blue/White/Red"
    : T extends "Radiant Crisis 001 Baseball Bat"
    ? "Default"
    : T extends "Nebula Knife"
    ? "Default"
    : T extends "Hack"
    ? "Default"
    : T extends "Glitchpop Dagger"
    ? "Default"
    : T extends "Glitchpop Axe"
    ? "Default"
    : T extends "Terminus A Quo"
    ? "Default" | "Purple" | "Red" | "Black"
    : T extends "Caeruleus"
    ? "Default"
    : T extends "Blade of Chaos"
    ? "Default" | "Green" | "White" | "Blue"
    : T extends "Elderflame Dagger"
    ? "Default"
    : T extends "Singularity Knife"
    ? "Default"
    : T extends "Blade of Serket"
    ? "Default"
    : T extends "Songsteel"
    ? "Default"
    : T extends "VCT LOCK//IN Misericórdia"
    ? "Default" | "Pacific" | "Americas" | "EMEA"
    : T extends "Hivemind Sword"
    ? "Default"
    : T extends "Venturi Knife"
    ? "Default"
    : T extends "Forsaken Ritual Blade"
    ? "Default"
    : T extends "Velocity Karambit"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Ruin Dagger"
    ? "Default"
    : T extends ".SYS Melee"
    ? "Default"
    : T extends "Neo Frontier Axe"
    ? "Default" | "Gold" | "Silver" | "Copper"
    : T extends "Soulstrife Scythe"
    ? "Default"
    : T extends "Prime Axe"
    ? "Default"
    : T extends "Prime//2.0 Karambit"
    ? "Default"
    : T extends "Outpost Melee"
    ? "Default"
    : T extends "Black.Market Butterfly Knife"
    ? "Default"
    : T extends "Bound "
    ? "Default"
    : T extends "Prism Knife"
    ? "Default"
    : T extends "Prism III Axe"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Broken Blade of the Ruined King"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Kingdom Knife"
    ? "Default"
    : T extends "K/TAC Blade"
    ? "Default"
    : T extends "Equilibrium"
    ? "Default" | "Dark"
    : T extends "Smite Knife"
    ? "Default"
    : T extends "Daydreams Crowbar"
    ? "Default"
    : T extends "Catrina"
    ? "Default" | "Living" | "Eternal"
    : T extends "Iridian Thorn Blade"
    ? "Default"
    : T extends "Celestial Fan"
    ? "Default"
    : T extends "Luxe Knife"
    ? "Default"
    : T extends "Magepunk Electroblade"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Magepunk Shock Gauntlet"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Magepunk Sparkswitch"
    ? "Default" | "Green" | "Black/Red" | "Yellow"
    : T extends "Spline Dagger"
    ? "Default"
    : T extends "Crimsonbeast Hammer"
    ? "Default"
    : T extends "Genesis Arc"
    ? "Default"
    : T extends "Ion Energy Sword"
    ? "Default"
    : T extends "Ion Karambit"
    ? "Default" | "Green" | "Yellow" | "Blue"
    : T extends "Oni Claw"
    ? "Default"
    : T extends "Onimaru Kunitsuna"
    ? "Default" | "Kumo" | "Hana" | "Tsubame"
    : T extends "Cryostasis Impact Drill"
    ? "Default"
    : T extends "Artisan Foil"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Personal Administrative Melee Unit"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Luna's Descent"
    ? "Default"
    : T extends "Random Favorite Skin"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Baton"
    ? "Default"
    : T extends "Relic of the Sentinel"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Snowfall Wand"
    ? "Default"
    : T extends "Reaver Knife"
    ? "Default"
    : T extends "Reaver Karambit"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Prosperity"
    ? "Default"
    : T extends "Sovereign Sword"
    ? "Default"
    : T extends "Recon Balisong"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Titanmail Mace"
    ? "Default"
    : T extends "Reverie Sword"
    ? "Default"
    : T extends "Melee"
    ? "Default"
    : T extends "Tilde Knife"
    ? "Default" | "Red" | "Purple" | "Green"
    : T extends "Hu Else"
    ? "Default"
    : T extends "NO LIMITS Bat"
    ? "Default"
    : T extends "BlastX Polymer KnifeTech Coated Knife"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Ego Knife"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Ignite Fan"
    ? "Default" | "Purple"
    : T extends "Winterwunderland Candy Cane"
    ? "Default" | "Green" | "Blue" | "Rainbow"
    : null;
