/* FILE GENERATED AUTOMATICALLY */

export type SprayType =
    | "Caught on Camera Spray"
    | "Chicken Out Spray"
    | "Defy the Limits Spray"
    | "G.O.A.T. Spray"
    | "Sad Crab Spray"
    | "No Time Spray"
    | "No Toxicity Spray"
    | "Dark Side Beyond Spray"
    | "Dap Team Spray"
    | "This is Also Fine Spray"
    | "Little Onion Lad Spray"
    | "Cheaters Never Prosper Spray"
    | "Wanted: Tactibunny Spray"
    | "8-bit VALORANT Spray"
    | "GGWP Spray"
    | "Mic Drop Spray"
    | "Step Under Here Spray"
    | "No Op Spray"
    | "Piece of Cake Spray"
    | "Pick My Strat Spray"
    | "Octorave Spray"
    | "Stellar Dendrite Spray"
    | "Thumbs Up Spray"
    | "Stay Safe, Wash Your Hands Spray"
    | "RGX 11z Pro Spray"
    | "RGX 11z Pro, Ep 4 Spray"
    | "Fierce Form Spray"
    | "Gekko Spray"
    | "Creature Crew Spray"
    | "Here I Am Spray"
    | "Bazooka Badger Spray"
    | "Dance Fever Spray"
    | "K.nock O.ut!! Spray"
    | "Gaia's Vengeance Spray"
    | "Spectrum Spray"
    | "Boom! Spray"
    | "Fade Spray"
    | "On the Prowl Spray"
    | "Eye Opener Spray"
    | "Breach Spray"
    | "K.O. Spray"
    | "Guns Out Spray"
    | "FTW Spray"
    | "Camper Spray"
    | "Excuse Me? Spray"
    | "Cheesy Shot Spray"
    | "Raze Spray"
    | "BoomShaka Spray"
    | "Bombshell Spray"
    | "Explorgi Spray"
    | "ChronoVoid Spray"
    | "Danger Spray"
    | "One In The Chamber Spray"
    | "Chamber Spray"
    | "Seeing Double Spray"
    | "VALORANT Spray"
    | "Prelude to Chaos Spray"
    | "Bruno Coin Spray"
    | "Doodle Buds // Tactifriends Spray"
    | "Doodle Buds // League of Legends Spray"
    | "Doodle Buds // Agents Spray"
    | "Elderflame Spray"
    | "Quack!! Spray"
    | "That's a Blowout Spray"
    | "A Perfect Score Spray"
    | "Just Jokin' Spray"
    | "Trailblazing Tiger Spray"
    | "Cool Joy Spray"
    | "Waddle Walk Spray"
    | "You Wanna Play? Spray"
    | "No Duelist No Problem Spray"
    | "Never Forget Leg Day Spray"
    | "Neon Bot Spray"
    | "No Spectre Spray"
    | "Nosey Neighbor Spray"
    | "Winner's Ribbon Spray"
    | "Sage Signal Spray"
    | "We Can Do It Spray"
    | "Dream Team Spray"
    | "Who's That Blind Spray"
    | "Definitely Not It Spray"
    | "Last Person Standing Spray"
    | "Perfectly Roasted Spray"
    | "Good Fortune Spray"
    | "Oh No Spray"
    | "No Bullets Spray"
    | "Network Error Spray"
    | "9 Lives Spray"
    | "No Worries Neon Spray"
    | "Shock Heart Spray"
    | "Drop Skin Please Spray"
    | "Gridcrash Spray"
    | "Oh Yes Spray"
    | "Blueberry Spray"
    | "Spicy Spray"
    | "Hershey Pup Spray"
    | "Choose my Weapon Spray"
    | "Glitch Out Chicken Spray"
    | "Make 'em Dance Spray"
    | "EZ Spray"
    | "Going C Spray"
    | "<3 Spray"
    | "Lit for 140 Spray"
    | "Faces in Places Spray"
    | "No Shorty Spray"
    | "Radianite Hazard Spray"
    | "What was that? Spray"
    | "Alas, poor Robot! Spray"
    | "Make Some Noise Spray"
    | "Chill Out Spray"
    | "Is This A Drone? Spray"
    | "Shhh! Spray"
    | "Do Not Enter Spray"
    | "Dumpster Fire Spray"
    | "/FF Spray"
    | "Epilogue: Super! Spray"
    | "Embarrassing! Spray"
    | "LAG! Spray"
    | "Happy Frog Spray"
    | "MY EYES! Spray"
    | "Revive Me, Jett! Spray"
    | "Super! Spray"
    | "Nope Spray"
    | "Approved! Spray"
    | "Lobster? Spray"
    | "Theo's Great Escape Spray"
    | "Bunny Hop Spray"
    | "Without a Trace Spray"
    | "Dabbing Dan Spray"
    | "Epilogue: Dabbing Dan Spray"
    | "Comedy and the Tragedy Spray"
    | "Songsteel Spray"
    | "Hang in There, Mance Spray"
    | "Nice Save Spray"
    | "Be Gone! Spray"
    | "No Odin Spray"
    | "This is Also Also Fine Spray"
    | "300 Spray"
    | "Walk! Don't Run Spray"
    | "Hardstuck Spray"
    | "Clutch or Kick Spray"
    | "Cracked Spray"
    | "Epilogue: Cracked Spray"
    | "Greatly Decreased? Spray"
    | "Sands of Time Spray"
    | "Killjoy! I Choose You! Spray"
    | "Max Money Spray"
    | "No Guardian Spray"
    | "No Pen Spray"
    | "Sand Sculpture Spray"
    | "Sova Says Sorry Spray"
    | "Surprised Penguin Spray"
    | "Pump Action Spray"
    | "Too Heavy Spray"
    | "Greatly Increased? Spray"
    | "Promises Kept Spray"
    | "Yikes Spray"
    | "Hooked Spray"
    | "Crispy Spray"
    | "Does Not Compute Spray"
    | "Hold Up Spray"
    | "Love > Hate Spray"
    | "Nice Try! Spray"
    | "No Judge Spray"
    | "OTL Spray"
    | "Artisan Spray"
    | "Trust in My Healing Spray"
    | "This is Not Fine Spray"
    | "To the Moon Spray"
    | "Not Impressed Spray"
    | "Volunteer Spray"
    | "Scavenger Spray"
    | "Mance on a Broom Go Zoom Spray"
    | "It's Lit Spray"
    | "Goldwing Spray"
    | "Countdown is On Spray"
    | "No Bucky Spray"
    | "With Love, Reyna Spray"
    | "Sad Yoru Spray"
    | "Trevor Gets It Spray"
    | "Turn it Up, Rudy Spray"
    | "Plant Plant Spray"
    | "Sugar Muffins Spray"
    | "Take My Creds! Spray"
    | "This is Really Not Fine Spray"
    | "Bad Hair Day Spray"
    | "Sweetest Match Spray"
    | "Head Slapper Spray"
    | "A Prime Valentine's Gift Spray"
    | "Hydrodip Spray"
    | "Jett-Bot Spray"
    | "Lost Connection Spray"
    | "Agent Down Spray"
    | "What's That? Spray"
    | "Potato Aim Spray"
    | "Missed a Spot Spray"
    | "Shoot Here Spray"
    | "Use Ult Spray"
    | "Woke Up Thinking Lineups Spray"
    | "Bruno's Happy Dance Spray"
    | "Hang Loose Spray"
    | "Crying Mance Spray"
    | "All Aboard Spray"
    | "Matcha Break Spray"
    | "Pros Don't Fake Spray"
    | "Sheeeeesh Spray"
    | "Slipping Away Spray"
    | "Stop! Spray"
    | "Tactibear's Balalaika Spray"
    | "Take a Bow Spray"
    | "Many Thanks Spray"
    | "Splitting Melons Spray"
    | "#SAVEWIDEJOY Spray"
    | "Epilogue: #SAVEWIDEJOY Spray"
    | "Caution: Blinding Bird! Spray"
    | "Cap? No Cap? Spray"
    | "Bawk Bawk Brimstone Spray"
    | "Keeping Secrets Spray"
    | "Backseat Coaching Spray"
    | "Heaven or Hell? Spray"
    | "I Have Three Creds Spray"
    | "Charge Needed Spray"
    | "Look Behind You Spray"
    | "Coalition: Cobra Spray"
    | "Pretty Pretty Please Spray"
    | "It's Stinger Time Spray"
    | "Epilogue: It's Stinger Time Spray"
    | "Terrible Day for Rain Spray"
    | "Don't Watch This Spray"
    | "Skeptical Viper Spray"
    | "Immortalized Spray"
    | "Hide the Pain, Brimstone Spray"
    | "Piedra del Sol Spray"
    | "Unamused Chamber Spray"
    | "Phoenix Rise Spray"
    | "I've Been Hit Spray"
    | "Hehehehehe Spray"
    | "Let Me In Spray"
    | "No Sentinels Spray"
    | "Very Sneaky Spray"
    | "Raze has Range Spray"
    | "Guess That's It Spray"
    | "Blasting Away Spray"
    | "Choose Your Match Spray"
    | "You Are Here Spray"
    | "Sketchy AFK Spray"
    | "Simple Instructions Spray"
    | "Hawk Out Spray"
    | "Always Watching Spray"
    | "Fascinating Spray"
    | "Breach's Approval Spray"
    | "Mind Blown Spray"
    | "No Vision Spray"
    | "Treat Those Burns Spray"
    | "Fill Your Card Spray"
    | "I Sleep Spray"
    | "Written in the Stars Spray"
    | "See You Next Round Spray"
    | "Surprise! It's a Tiger Spray"
    | "Unconditional Surrender Spray"
    | "Huh? Spray"
    | "Dolla Dolla Bill Y'all Spray"
    | "Tug of War Spray"
    | "Wide Swing Spray"
    | "We Made it Spray"
    | "Well Played Spray"
    | "Omen Cat Dance Spray"
    | "Let's Go! Spray"
    | "Signature Spray"
    | "Charging Station Spray"
    | "Scoop of Smoke Spray"
    | "Wanted: Tactibear Spray"
    | "Bye Op Spray"
    | "Too Early for This Spray"
    | "Whaaat? Spray"
    | "Am I Clear? Spray"
    | "Peace Out Spray"
    | "Not Your Healer Spray"
    | "Nothing to See Here Spray"
    | "Bound Spray"
    | "Already Locked Spray"
    | "Don't Look Back Spray"
    | "Perfect Disaster Spray"
    | "Monstrocity Spray"
    | "I'm Melting Spray"
    | "Omen Remembers Spray"
    | "Moondash Spray"
    | "Put it on my Card Spray"
    | "Nice! Spray"
    | "Whack a Squirrel Spray"
    | "Champions 2022 Jett Diff Spray"
    | "VCT 2021 Spark Spray"
    | "Fakeout Spray"
    | "Fist Bump Spray"
    | "Team Ace // Jett Spray"
    | "Team Ace // Phoenix Spray"
    | "Team Ace // Raze Spray"
    | "Team Ace // Reyna Spray"
    | "Team Ace // Yoru Spray"
    | "GG Shooter Spray"
    | "GLHF Spray"
    | "Give Back // 2022 Spray"
    | "Googly Moogly Spray"
    | "KAY/O Spray"
    | "Drained Spray"
    | "Training Bot Spray"
    | "Wild Life Spray"
    | "On Your Trail Spray"
    | "Skye Spray"
    | "Cypher Spray"
    | "The Seeker Spray"
    | "I See You Spray"
    | "Soulstrife Spray"
    | "Lethal Crosshair Spray"
    | "Calculated Spray"
    | "Sova Spray"
    | "Take Flight Spray"
    | "On Target Spray"
    | "Prime Brick Spray"
    | "Doomscrolling Spray"
    | "Killjoy Spray"
    | "Variable Removed Spray"
    | "Don't Cross Me Spray"
    | "Matsuba Spray"
    | "Kohaku Spray"
    | "Lights Out Spray"
    | "Lucky Tiger Spray"
    | "Celestial Spray"
    | "Stay Hydrated Spray"
    | "Harbor Spray"
    | "That's a Six Spray"
    | "Magepunk, Ep 3 Spray"
    | "Claw and Order Spray"
    | "Champions 2022 Curse Spray"
    | "Flames in my Veins Spray"
    | "Runnin' on Empty Spray"
    | "Just Business Spray"
    | "Sic' Em Spray"
    | "Give Back Spray"
    | "Ego or Eco Spray"
    | "Shreddy Teddy Spray"
    | "Pity Party Spray"
    | "Tag! You're Dead! Spray"
    | "Crimsonbeast Spray"
    | "Nice One Spray"
    | "Octo Attack 2 Spray"
    | "Pick Your Poison Spray"
    | "Deadly Venom Spray"
    | "Viper Spray"
    | "Phoenix Spray"
    | "Claim the Crown Spray"
    | "Spotlight Spray"
    | "Too Easy Spray"
    | "Protocol 781-A Spray"
    | "Clutch Spray"
    | "Astral Plane Spray"
    | "Astra Spray"
    | "Galaxy Brain Spray"
    | "Salt Shaker Spray"
    | "Brimstone Spray"
    | "The Big One Spray"
    | "Getting Reps Spray"
    | "Loose Cannon Spray"
    | "VALORANT GO! Vol. 1 Cypher Spray"
    | "VALORANT GO! Vol. 1 Jett Spray"
    | "VALORANT GO! Vol. 1 Killjoy Spray"
    | "VALORANT GO! Vol. 1 Reyna Spray"
    | "VALORANT GO! Vol. 1 Sage Spray"
    | "VALORANT GO! Vol. 2 Phoenix Spray"
    | "VALORANT GO! Vol. 2 Raze Spray"
    | "VALORANT GO! Vol. 2 Sova Spray"
    | "VALORANT GO! Vol. 2 Viper Spray"
    | "VALORANT GO! Vol. 2 Yoru Spray"
    | "Araxys Spray"
    | "Champions 2022 Spray"
    | "Origin Spray"
    | "Glitchpop Spray"
    | "Glitchpop, EP 2 Spray"
    | "Singularity Spray"
    | "VCT LOCK//IN Vamos! Spray"
    | "Forsaken Spray"
    | "Ruin Spray"
    | "Prime//2.0 Spray"
    | "Ruination Spray"
    | "Magepunk Spray"
    | "Spline Spray"
    | "Ion Spray"
    | "Ion, Ep5 Spray"
    | "Oni Spray"
    | "Oni, Ep 6 Spray"
    | "Luna Spray"
    | "Gravitational Uranium Neuroblaster Spray"
    | "Sentinels of Light Spray"
    | "Reaver Spray"
    | "Ego Spray"
    | "BlastX Spray"
    | "Reaver, EP 5 Spray"
    | "Sovereign Spray"
    | "Clip It Spray"
    | "Neon Spray"
    | "Hot Mic Spray"
    | "Nice to Zap You Spray"
    | "Who's Next Spray"
    | "Sharp Spray"
    | "Yoru Spray"
    | "200 IQ Spray"
    | "Tactibear Spray"
    | "Sage Spray"
    | "All Good Spray"
    | "Pulse Check Spray"
    | "Tigris Spray"
    | "No Spray Equipped"
    | "V for VALORANT Spray"
    | "Can't Teach That Spray"
    | "Reyna Spray"
    | "Leer Spray"
    | "Marked for Death Spray"
    | "Vandal Life Spray"
    | "Accidental Renaissance Spray"
    | "Omen Spray"
    | "It Hunts Spray"
    | "Dark Focus Spray"
    | "Jett Spray"
    | "Watch This Spray"
    | "You Better Run Spray";
